// AUTOGENERATED by 'node bootstrap.js prelude-types'
/**
```
@ffi("Vec2") type Vec2#08f7c2ac = {
    x: float#builtin,
    y: float#builtin,
}
```
*/
type t_08f7c2ac = {
  type: "Vec2";
  x: number;
  y: number;
};

/**
```
@ffi("End") type End#830ad468 = {}
```
*/
type t_830ad468 = {
  type: "End";
};

/**
```
@ffi("Start") type Start#098d99e8 = {}
```
*/
type t_098d99e8 = {
  type: "Start";
};

/**
```
@ffi("Center") type Center#1189540a = {}
```
*/
type t_1189540a = {
  type: "Center";
};

/**
```
@ffi("Right") type Right#5cfc662e = {}
```
*/
type t_5cfc662e = {
  type: "Right";
};

/**
```
@ffi("Left") type Left#43051e9e = {}
```
*/
type t_43051e9e = {
  type: "Left";
};

/**
```
@ffi("Rgba") type Rgba#52033f94 = {
    r: float#builtin,
    g: float#builtin,
    b: float#builtin,
    a: float#builtin = 1.0,
}
```
*/
type t_52033f94 = {
  type: "Rgba";
  r: number;
  g: number;
  b: number;
  a: number;
};

/**
```
@ffi("CSS") type CSS#742a31c2 = {
    value: string#builtin,
}
```
*/
type t_742a31c2 = {
  type: "CSS";
  value: string;
};

/**
```
@ffi("Square") type Square#155bb0ac = {}
```
*/
type t_155bb0ac = {
  type: "Square";
};

/**
```
@ffi("Round") type Round#51486760 = {}
```
*/
type t_51486760 = {
  type: "Round";
};

/**
```
@ffi("Butt") type Butt#1ac05bf8 = {}
```
*/
type t_1ac05bf8 = {
  type: "Butt";
};

/**
```
@ffi("Path") type Path#ddadd8a8 = {
    start: Vec2#08f7c2ac,
    closed: bool#builtin = false,
    parts: Array#builtin<PathPart#33159eb4>,
}
```
*/
type t_ddadd8a8 = {
  type: "Path";
  start: t_08f7c2ac;
  closed: boolean;
  parts: Array<t_33159eb4>;
};

/**
```
@ffi("Rect") type Rect#126fdf00 = {
    pos: Vec2#08f7c2ac,
    size: Vec2#08f7c2ac,
    rotation: float#builtin = 0.0,
}
```
*/
type t_126fdf00 = {
  type: "Rect";
  pos: t_08f7c2ac;
  size: t_08f7c2ac;
  rotation: number;
};

/**
```
@ffi("Polygon") type Polygon#cafe28b8 = {
    points: Array#builtin<Vec2#08f7c2ac>,
    closed: bool#builtin = true,
}
```
*/
type t_cafe28b8 = {
  type: "Polygon";
  points: Array<t_08f7c2ac>;
  closed: boolean;
};

/**
```
@ffi("Line") type Line#565da092 = {
    p1: Vec2#08f7c2ac,
    p2: Vec2#08f7c2ac,
}
```
*/
type t_565da092 = {
  type: "Line";
  p1: t_08f7c2ac;
  p2: t_08f7c2ac;
};

/**
```
@ffi("Ellipse") type Ellipse#098fbabc = {
    pos: Vec2#08f7c2ac,
    radius: Vec2#08f7c2ac,
    rotation: float#builtin = 0.0,
}
```
*/
type t_098fbabc = {
  type: "Ellipse";
  pos: t_08f7c2ac;
  radius: t_08f7c2ac;
  rotation: number;
};

/*enum TextAlign#eaefd106 {
    Left#43051e9e,
    Right#5cfc662e,
    Center#1189540a,
    Start#098d99e8,
    End#830ad468,
}*/
type t_eaefd106 = t_43051e9e | t_5cfc662e | t_1189540a | t_098d99e8 | t_830ad468;

/*enum Color#1fe34118 {
    CSS#742a31c2,
    Rgba#52033f94,
}*/
type t_1fe34118 = t_742a31c2 | t_52033f94;

/*enum LineCap#5e11f0b9 {
    Butt#1ac05bf8,
    Round#51486760,
    Square#155bb0ac,
}*/
type t_5e11f0b9 = t_1ac05bf8 | t_51486760 | t_155bb0ac;

/*enum Geom#619d2fc4 {
    Ellipse#098fbabc,
    Line#565da092,
    Polygon#cafe28b8,
    Rect#126fdf00,
    Path#ddadd8a8,
}*/
type t_619d2fc4 = t_098fbabc | t_565da092 | t_cafe28b8 | t_126fdf00 | t_ddadd8a8;

/**
```
@ffi("Arc") type Arc#443a6bbd = {
    center: Vec2#08f7c2ac,
    startAngle: float#builtin,
    endAngle: float#builtin,
    counterClockwise: bool#builtin = false,
}
```
*/
type t_443a6bbd = {
  type: "Arc";
  center: t_08f7c2ac;
  startAngle: number;
  endAngle: number;
  counterClockwise: boolean;
};

/**
```
@ffi("Text") type Text#d86ebaa8 = {
    text: string#builtin,
    color: Color#1fe34118,
    pos: Vec2#08f7c2ac,
    stroke: float#builtin = 0.0,
    font: string#builtin = "",
    textAlign: TextAlign#eaefd106 = TextAlign#eaefd106:Start#098d99e8,
}
```
*/
type t_d86ebaa8 = {
  type: "Text";
  text: string;
  color: t_1fe34118;
  pos: t_08f7c2ac;
  stroke: number;
  font: string;
  textAlign: t_eaefd106;
};

/**
```
@ffi("Stroke") type Stroke#adcc8cc6 = {
    geom: Geom#619d2fc4,
    color: Color#1fe34118,
    width: float#builtin = 1.0,
    lineCaps: LineCap#5e11f0b9 = LineCap#5e11f0b9:Round#51486760,
}
```
*/
type t_adcc8cc6 = {
  type: "Stroke";
  geom: t_619d2fc4;
  color: t_1fe34118;
  width: number;
  lineCaps: t_5e11f0b9;
};

/**
```
@ffi("Fill") type Fill#3bd0cc4c = {
    geom: Geom#619d2fc4,
    color: Color#1fe34118,
}
```
*/
type t_3bd0cc4c = {
  type: "Fill";
  geom: t_619d2fc4;
  color: t_1fe34118;
};

/**
```
@ffi("EllipsePath") type EllipsePath#92791c88 = {
    ...Arc#443a6bbd,
    radius: Vec2#08f7c2ac,
    rotation: float#builtin,
}
```
*/
type t_92791c88 = {
  type: "EllipsePath";
  radius: t_08f7c2ac;
  rotation: number;
  center: t_08f7c2ac;
  startAngle: number;
  endAngle: number;
  counterClockwise: boolean;
};

/**
```
@ffi("Rounded") type Rounded#b7a4f230 = {
    c1: Vec2#08f7c2ac,
    c2: Vec2#08f7c2ac,
    radius: float#builtin,
}
```
*/
type t_b7a4f230 = {
  type: "Rounded";
  c1: t_08f7c2ac;
  c2: t_08f7c2ac;
  radius: number;
};

/**
```
@ffi("Bezier") type Bezier#37a1f256 = {
    c1: Vec2#08f7c2ac,
    c2: Vec2#08f7c2ac,
    c3: Vec2#08f7c2ac,
    c4: Vec2#08f7c2ac,
    end: Vec2#08f7c2ac,
}
```
*/
type t_37a1f256 = {
  type: "Bezier";
  c1: t_08f7c2ac;
  c2: t_08f7c2ac;
  c3: t_08f7c2ac;
  c4: t_08f7c2ac;
  end: t_08f7c2ac;
};

/**
```
@ffi("Quadratic") type Quadratic#5c0c4fd8 = {
    control: Vec2#08f7c2ac,
    end: Vec2#08f7c2ac,
}
```
*/
type t_5c0c4fd8 = {
  type: "Quadratic";
  control: t_08f7c2ac;
  end: t_08f7c2ac;
};

/**
```
@ffi("CanvasScene") type CanvasScene#7c9e2d1c<State#:0> = {
    initial: State#:0,
    update: (state: State#:0, dt: float#builtin) ={}> State#:0,
    draw: (state: State#:0) ={}> Array#builtin<Drawable#56de3b71>,
    clear: bool#builtin = true,
    fps: float#builtin = 60.0,
    size: Vec2#08f7c2ac = Vec2#08f7c2ac{x#08f7c2ac#0: 200, y#08f7c2ac#1: 200},
}
```
*/
type t_7c9e2d1c<T_0> = {
  type: "CanvasScene";
  initial: T_0;
  update: (arg_0: T_0, arg_1: number) => T_0;
  draw: (arg_0: T_0) => Array<t_56de3b71>;
  clear: boolean;
  fps: number;
  size: t_08f7c2ac;
};

/*enum Drawable#56de3b71 {
    Fill#3bd0cc4c,
    Stroke#adcc8cc6,
    Text#d86ebaa8,
}*/
type t_56de3b71 = t_3bd0cc4c | t_adcc8cc6 | t_d86ebaa8;

/*enum PathPart#33159eb4 {
    Vec2#08f7c2ac,
    Quadratic#5c0c4fd8,
    Bezier#37a1f256,
    Rounded#b7a4f230,
    Arc#443a6bbd,
    EllipsePath#92791c88,
}*/
type t_33159eb4 = t_08f7c2ac | t_5c0c4fd8 | t_37a1f256 | t_b7a4f230 | t_443a6bbd | t_92791c88;

/**
```
type Some#Some<T#:10000> = {
    contents: T#:10000,
}
```
*/
type t_Some<T_10000> = {
  type: "Some";
  hSome_0: T_10000;
};

/**
```
type None#None = {}
```
*/
type t_None = {
  type: "None";
};

/**
```
type As#As<T#:10000, Y#:10001> = {
    as: (T#:10000) ={}> Y#:10001,
}
```
*/
type t_As<T_10000, T_10001> = {
  type: "As";
  hAs_0: (arg_0: T_10000) => T_10001;
};
export const As_id = "As";
export type As<T0, T1> = t_As<T0, T1>;
export const Some_id = "Some";
export type Some<T0> = t_Some<T0>;
export const None_id = "None";
export type None = t_None;
export const Vec2_id = "08f7c2ac";
export type Vec2 = t_08f7c2ac;
export const Arc_id = "443a6bbd";
export type Arc = t_443a6bbd;
export const CSS_id = "742a31c2";
export type CSS = t_742a31c2;
export const Rgba_id = "52033f94";
export type Rgba = t_52033f94;
export const Color_id = "1fe34118";
export type Color = t_1fe34118;
export const Quadratic_id = "5c0c4fd8";
export type Quadratic = t_5c0c4fd8;
export const Bezier_id = "37a1f256";
export type Bezier = t_37a1f256;
export const Rounded_id = "b7a4f230";
export type Rounded = t_b7a4f230;
export const EllipsePath_id = "92791c88";
export type EllipsePath = t_92791c88;
export const PathPart_id = "33159eb4";
export type PathPart = t_33159eb4;
export const Path_id = "ddadd8a8";
export type Path = t_ddadd8a8;
export const Ellipse_id = "098fbabc";
export type Ellipse = t_098fbabc;
export const Line_id = "565da092";
export type Line = t_565da092;
export const Polygon_id = "cafe28b8";
export type Polygon = t_cafe28b8;
export const Rect_id = "126fdf00";
export type Rect = t_126fdf00;
export const Geom_id = "619d2fc4";
export type Geom = t_619d2fc4;
export const Fill_id = "3bd0cc4c";
export type Fill = t_3bd0cc4c;
export const Butt_id = "1ac05bf8";
export type Butt = t_1ac05bf8;
export const Round_id = "51486760";
export type Round = t_51486760;
export const Square_id = "155bb0ac";
export type Square = t_155bb0ac;
export const LineCap_id = "5e11f0b9";
export type LineCap = t_5e11f0b9;
export const Stroke_id = "adcc8cc6";
export type Stroke = t_adcc8cc6;
export const Left_id = "43051e9e";
export type Left = t_43051e9e;
export const Right_id = "5cfc662e";
export type Right = t_5cfc662e;
export const Center_id = "1189540a";
export type Center = t_1189540a;
export const Start_id = "098d99e8";
export type Start = t_098d99e8;
export const End_id = "830ad468";
export type End = t_830ad468;
export const TextAlign_id = "eaefd106";
export type TextAlign = t_eaefd106;
export const Text_id = "d86ebaa8";
export type Text = t_d86ebaa8;
export const Drawable_id = "56de3b71";
export type Drawable = t_56de3b71;
export const CanvasScene_id = "7c9e2d1c";
export type CanvasScene<T0> = t_7c9e2d1c<T0>;