// AUTOGENERATED by 'node bootstrap.js prelude-types'
export type sampler2D = {[y: number]: {[x: number]: Vec4}};
/**
```
@ffi("Vec2") type Vec2#78566d10 = {
    x: float#builtin,
    y: float#builtin,
}
```
*/
type t_78566d10 = {
  type: "Vec2";
  x: number;
  y: number;
};

/**
```
@ffi("XY") type XY#00d6d092<State#:0> = {
    min: Vec2#78566d10,
    max: Vec2#78566d10,
    update: (state: State#:0, pos: Vec2#78566d10) ={}> State#:0,
}
```
*/
type t_00d6d092<State> = {
  type: "XY";
  min: t_78566d10;
  max: t_78566d10;
  update: (arg_0: State, arg_1: t_78566d10) => State;
};

/**
```
@ffi("Options") type Options#1ec5b16c<State#:0> = {
    names: Array#builtin<string#builtin>,
    update: (state: State#:0, idx: int#builtin) ={}> State#:0,
}
```
*/
type t_1ec5b16c<State> = {
  type: "Options";
  names: Array<string>;
  update: (arg_0: State, arg_1: number) => State;
};

/**
```
@ffi("Int") type Int#a30fcf78<State#:0> = {
    min: int#builtin,
    max: int#builtin,
    step: int#builtin,
    update: (state: State#:0, value: int#builtin) ={}> State#:0,
}
```
*/
type t_a30fcf78<State> = {
  type: "Int";
  min: number;
  max: number;
  step: number;
  update: (arg_0: State, arg_1: number) => State;
};

/**
```
@ffi("Float") type Float#95e461ee<State#:0> = {
    min: float#builtin,
    max: float#builtin,
    step: float#builtin,
    update: (state: State#:0, value: float#builtin) ={}> State#:0,
}
```
*/
type t_95e461ee<State> = {
  type: "Float";
  min: number;
  max: number;
  step: number;
  update: (arg_0: State, arg_1: number) => State;
};

/**
```
@ffi("Angle") type Angle#1f79d016<State#:0> = {
    step: float#builtin,
    update: (state: State#:0, angle: float#builtin) ={}> State#:0,
}
```
*/
type t_1f79d016<State> = {
  type: "Angle";
  step: number;
  update: (arg_0: State, arg_1: number) => State;
};

/**
```
@ffi("Vec3") type Vec3#1b597af1 = {
    ...Vec2#78566d10,
    z: float#builtin,
}
```
*/
type t_1b597af1 = {
  type: "Vec3";
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("MouseButton") type MouseButton#0d2756fc = {
    button: int#builtin,
    down: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_0d2756fc = {
  type: "MouseButton";
  button: number;
  down: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/**
```
@ffi("KeyEvent") type KeyEvent#63e792d4 = {
    key: string#builtin,
    press: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_63e792d4 = {
  type: "KeyEvent";
  key: string;
  press: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/*enum WidgetConfig#2faeebde<State#:0> {
    Angle#1f79d016<State#:0>,
    Float#95e461ee<State#:0>,
    Int#a30fcf78<State#:0>,
    Options#1ec5b16c<State#:0>,
    XY#00d6d092<State#:0>,
}*/
type t_2faeebde<State> = t_1f79d016<State> | t_95e461ee<State> | t_a30fcf78<State> | t_1ec5b16c<State> | t_00d6d092<State>;

/**
```
@ffi("Vec4") type Vec4#38dc9122 = {
    ...Vec3#1b597af1,
    w: float#builtin,
}
```
*/
type t_38dc9122 = {
  type: "Vec4";
  w: number;
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("GLSLScene") type GLSLScene#6ca4b54c<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#269f3dcc<T#:0>, GLSLEnv#269f3dcc<T#:0>, Array#builtin<GLSLEvent#837ab94c>) ={}> T#:0,
    render: (GLSLEnv#269f3dcc<T#:0>, Vec2#78566d10) ={}> Vec4#38dc9122,
}
```
*/
type t_6ca4b54c<T> = {
  type: "GLSLScene";
  initial: T;
  step: (arg_0: t_269f3dcc<T>, arg_1: t_269f3dcc<T>, arg_2: Array<t_837ab94c>) => T;
  render: (arg_0: t_269f3dcc<T>, arg_1: t_78566d10) => t_38dc9122;
};

/*enum GLSLEvent#837ab94c {
    KeyEvent#63e792d4,
    MouseButton#0d2756fc,
}*/
type t_837ab94c = t_63e792d4 | t_0d2756fc;

/**
```
@ffi("GLSLScene") type GLSLSceneOld#d828bc9e<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#269f3dcc<T#:0>, GLSLEnv#269f3dcc<T#:0>) ={}> T#:0,
    render: (GLSLEnv#269f3dcc<T#:0>, Vec2#78566d10) ={}> Vec4#38dc9122,
}
```
*/
type t_d828bc9e<T> = {
  type: "GLSLScene";
  initial: T;
  step: (arg_0: t_269f3dcc<T>, arg_1: t_269f3dcc<T>) => T;
  render: (arg_0: t_269f3dcc<T>, arg_1: t_78566d10) => t_38dc9122;
};

/**
```
@ffi("Widget") type Widget#2a10b434<State#:0> = {
    name: string#builtin,
    config: WidgetConfig#2faeebde<State#:0>,
}
```
*/
type t_2a10b434<State> = {
  type: "Widget";
  name: string;
  config: t_2faeebde<State>;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#269f3dcc<T#:0> = {
    state: T#:0,
    time: float#builtin,
    resolution: Vec2#78566d10,
    camera: Vec3#1b597af1,
    mouse: Vec2#78566d10,
    mouseButton: int#builtin,
}
```
*/
type t_269f3dcc<T> = {
  type: "GLSLEnv";
  state: T;
  time: number;
  resolution: t_78566d10;
  camera: t_1b597af1;
  mouse: t_78566d10;
  mouseButton: number;
};

/**
```
@ffi("GLSLBuffer1") type GLSLBuffer1#c2641774 = {
    fragment: (GLSLEnv#5cec7724, Vec2#78566d10, sampler2D#builtin) ={}> Vec4#38dc9122,
    buffer0: (GLSLEnv#5cec7724, Vec2#78566d10, sampler2D#builtin) ={}> Vec4#38dc9122,
}
```
*/
type t_c2641774 = {
  type: "GLSLBuffer1";
  fragment: (arg_0: t_5cec7724, arg_1: t_78566d10, arg_2: sampler2D) => t_38dc9122;
  buffer0: (arg_0: t_5cec7724, arg_1: t_78566d10, arg_2: sampler2D) => t_38dc9122;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#5cec7724 = {
    time: float#builtin,
    resolution: Vec2#78566d10,
    camera: Vec3#1b597af1,
    mouse: Vec2#78566d10,
}
```
*/
type t_5cec7724 = {
  type: "GLSLEnv";
  time: number;
  resolution: t_78566d10;
  camera: t_1b597af1;
  mouse: t_78566d10;
};

/**
```
@unique(3) type Ord#2217571a<A#:0, B#:1> = {
    "<": (A#:0, B#:1) ={}> bool#builtin,
    ">": (A#:0, B#:1) ={}> bool#builtin,
    "<=": (A#:0, B#:1) ={}> bool#builtin,
    ">=": (A#:0, B#:1) ={}> bool#builtin,
}
```
*/
type t_2217571a<A, B> = {
  type: "2217571a";
  h2217571a_0: (arg_0: A, arg_1: B) => boolean;
  h2217571a_1: (arg_0: A, arg_1: B) => boolean;
  h2217571a_2: (arg_0: A, arg_1: B) => boolean;
  h2217571a_3: (arg_0: A, arg_1: B) => boolean;
};

/**
```
@unique(3) type Neg#f6e074a4<A#:0, B#:1> = {
    "-": (A#:0) ={}> B#:1,
}
```
*/
type t_f6e074a4<A, B> = {
  type: "f6e074a4";
  hf6e074a4_0: (arg_0: A) => B;
};

/**
```
@unique(2) type Div#2b90cfd4<A#:0, B#:1, C#:2> = {
    "/": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_2b90cfd4<A, B, C> = {
  type: "2b90cfd4";
  h2b90cfd4_0: (arg_0: A, arg_1: B) => C;
};

/**
```
@unique(1) type Mul#49fef1f5<A#:0, B#:1, C#:2> = {
    "*": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_49fef1f5<A, B, C> = {
  type: "49fef1f5";
  h49fef1f5_0: (arg_0: A, arg_1: B) => C;
};

/**
```
@unique(0) type AddSub#70e0d6d0<A#:0, B#:1, C#:2> = {
    "+": (A#:0, B#:1) ={}> C#:2,
    "-": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_70e0d6d0<A, B, C> = {
  type: "70e0d6d0";
  h70e0d6d0_0: (arg_0: A, arg_1: B) => C;
  h70e0d6d0_1: (arg_0: A, arg_1: B) => C;
};

/**
```
@ffi("Mat4") type Mat4#314455dc = {
    r1: Vec4#38dc9122,
    r2: Vec4#38dc9122,
    r3: Vec4#38dc9122,
    r4: Vec4#38dc9122,
}
```
*/
type t_314455dc = {
  type: "Mat4";
  r1: t_38dc9122;
  r2: t_38dc9122;
  r3: t_38dc9122;
  r4: t_38dc9122;
};

/**
```
@unique(0.5383562320075749) type Eq#2f333afa<T#:0> = {
    "==": (T#:0, T#:0) ={}> bool#builtin,
}
```
*/
type t_2f333afa<T> = {
  type: "2f333afa";
  h2f333afa_0: (arg_0: T, arg_1: T) => boolean;
};

/**
```
@unique(0.14972816008023876) type ToInt#691302fa<T#:0> = {
    int: (T#:0) ={}> int#builtin,
}
```
*/
type t_691302fa<T> = {
  type: "691302fa";
  h691302fa_0: (arg_0: T) => number;
};

/**
```
@unique(0.8408403012585762) type ToFloat#01b9d44e<T#:0> = {
    float: (T#:0) ={}> float#builtin,
}
```
*/
type t_01b9d44e<T> = {
  type: "01b9d44e";
  h01b9d44e_0: (arg_0: T) => number;
};

/**
```
@unique(0.5661807692527293) type ToStr#dce9d62c<T#:0> = {
    str: (T#:0) ={}> string#builtin,
}
```
*/
type t_dce9d62c<T> = {
  type: "dce9d62c";
  hdce9d62c_0: (arg_0: T) => string;
};

/**
```
@unique(0) type Some#Some<T#:10000> = {
    contents: T#:10000,
}
```
*/
type t_Some<T> = {
  type: "Some";
  hSome_0: T;
};

/**
```
@unique(1) type None#None = {}
```
*/
type t_None = {
  type: "None";
};

/**
```
@unique(2) type As#As<T#:10000, Y#:10001> = {
    as: (T#:10000) ={}> Y#:10001,
}
```
*/
type t_As<T, Y> = {
  type: "As";
  hAs_0: (arg_0: T) => Y;
};
export const As_id = "As";
export type As<T, Y> = t_As<T, Y>;
export const Some_id = "Some";
export type Some<T> = t_Some<T>;
export const None_id = "None";
export type None = t_None;
export const ToStr_id = "dce9d62c";
export type ToStr<T> = t_dce9d62c<T>;
export const ToFloat_id = "01b9d44e";
export type ToFloat<T> = t_01b9d44e<T>;
export const ToInt_id = "691302fa";
export type ToInt<T> = t_691302fa<T>;
export const Eq_id = "2f333afa";
export type Eq<T> = t_2f333afa<T>;
export const Vec2_id = "78566d10";
export type Vec2 = t_78566d10;
export const Vec3_id = "1b597af1";
export type Vec3 = t_1b597af1;
export const Vec4_id = "38dc9122";
export type Vec4 = t_38dc9122;
export const Mat4_id = "314455dc";
export type Mat4 = t_314455dc;
export const AddSub_id = "70e0d6d0";
export type AddSub<A, B, C> = t_70e0d6d0<A, B, C>;
export const Mul_id = "49fef1f5";
export type Mul<A, B, C> = t_49fef1f5<A, B, C>;
export const Div_id = "2b90cfd4";
export type Div<A, B, C> = t_2b90cfd4<A, B, C>;
export const Neg_id = "f6e074a4";
export type Neg<A, B> = t_f6e074a4<A, B>;
export const Ord_id = "2217571a";
export type Ord<A, B> = t_2217571a<A, B>;
export const GLSLEnv_id = "269f3dcc";
export type GLSLEnv<T> = t_269f3dcc<T>;
export const GLSLEnv$1_id = "5cec7724";
export type GLSLEnv$1 = t_5cec7724;
export const GLSLBuffer1_id = "c2641774";
export type GLSLBuffer1 = t_c2641774;
export const Angle_id = "1f79d016";
export type Angle<State> = t_1f79d016<State>;
export const Int_id = "a30fcf78";
export type Int<State> = t_a30fcf78<State>;
export const Float_id = "95e461ee";
export type Float<State> = t_95e461ee<State>;
export const Options_id = "1ec5b16c";
export type Options<State> = t_1ec5b16c<State>;
export const XY_id = "00d6d092";
export type XY<State> = t_00d6d092<State>;
export const WidgetConfig_id = "2faeebde";
export type WidgetConfig<State> = t_2faeebde<State>;
export const Widget_id = "2a10b434";
export type Widget<State> = t_2a10b434<State>;
export const GLSLSceneOld_id = "d828bc9e";
export type GLSLSceneOld<T> = t_d828bc9e<T>;
export const KeyEvent_id = "63e792d4";
export type KeyEvent = t_63e792d4;
export const MouseButton_id = "0d2756fc";
export type MouseButton = t_0d2756fc;
export const GLSLEvent_id = "837ab94c";
export type GLSLEvent = t_837ab94c;
export const GLSLScene_id = "6ca4b54c";
export type GLSLScene<T> = t_6ca4b54c<T>;
export const alternates_id = "4be372cc";
export const slider_id = "bb57eb62";
export const slider$1_id = "b981a438";
export const slider$2_id = "4e421b50";
export const rgb_id = "0e56d7de";
export const rgba_id = "1e399678";
export const hsl_id = "0a03820e";
export const hsla_id = "054ed17e";
export const title_id = "1b6d573e";
export const display_id = "62c51cb0";