// AUTOGENERATED by 'node bootstrap.js prelude-types'
export type sampler2D = {[y: number]: {[x: number]: Vec4}};
/**
```
@ffi("Vec2") type Vec2#43802a16 = {
    x: float#builtin,
    y: float#builtin,
}
```
*/
type t_43802a16 = {
  type: "Vec2";
  x: number;
  y: number;
};

/**
```
@ffi("Vec3") type Vec3#9f1c0644 = {
    ...Vec2#43802a16,
    z: float#builtin,
}
```
*/
type t_9f1c0644 = {
  type: "Vec3";
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("MouseButton") type MouseButton#326e13e1 = {
    button: int#builtin,
    down: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_326e13e1 = {
  type: "MouseButton";
  button: number;
  down: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/**
```
@ffi("KeyEvent") type KeyEvent#3648d5cc = {
    key: string#builtin,
    press: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_3648d5cc = {
  type: "KeyEvent";
  key: string;
  press: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/**
```
@ffi("Vec4") type Vec4#3b941378 = {
    ...Vec3#9f1c0644,
    w: float#builtin,
}
```
*/
type t_3b941378 = {
  type: "Vec4";
  w: number;
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("GLSLScene") type GLSLScene#7769219c<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#d2ea39a0<T#:0>, GLSLEnv#d2ea39a0<T#:0>, Array#builtin<GLSLEvent#4deab8f1>) ={}> T#:0,
    render: (GLSLEnv#d2ea39a0<T#:0>, Vec2#43802a16) ={}> Vec4#3b941378,
}
```
*/
type t_7769219c<T_0> = {
  type: "GLSLScene";
  initial: T_0;
  step: (arg_0: t_d2ea39a0<T_0>, arg_1: t_d2ea39a0<T_0>, arg_2: Array<t_4deab8f1>) => T_0;
  render: (arg_0: t_d2ea39a0<T_0>, arg_1: t_43802a16) => t_3b941378;
};

/*enum GLSLEvent#4deab8f1 {
    KeyEvent#3648d5cc,
    MouseButton#326e13e1,
}*/
type t_4deab8f1 = t_3648d5cc | t_326e13e1;

/**
```
@ffi("GLSLScene") type GLSLSceneOld#7eb87aa6<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#d2ea39a0<T#:0>, GLSLEnv#d2ea39a0<T#:0>) ={}> T#:0,
    render: (GLSLEnv#d2ea39a0<T#:0>, Vec2#43802a16) ={}> Vec4#3b941378,
}
```
*/
type t_7eb87aa6<T_0> = {
  type: "GLSLScene";
  initial: T_0;
  step: (arg_0: t_d2ea39a0<T_0>, arg_1: t_d2ea39a0<T_0>) => T_0;
  render: (arg_0: t_d2ea39a0<T_0>, arg_1: t_43802a16) => t_3b941378;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#d2ea39a0<T#:0> = {
    state: T#:0,
    time: float#builtin,
    resolution: Vec2#43802a16,
    camera: Vec3#9f1c0644,
    mouse: Vec2#43802a16,
    mouseButton: int#builtin,
}
```
*/
type t_d2ea39a0<T_0> = {
  type: "GLSLEnv";
  state: T_0;
  time: number;
  resolution: t_43802a16;
  camera: t_9f1c0644;
  mouse: t_43802a16;
  mouseButton: number;
};

/**
```
@ffi("GLSLBuffer1") type GLSLBuffer1#4dccf345 = {
    fragment: (GLSLEnv#451d5252, Vec2#43802a16, sampler2D#builtin) ={}> Vec4#3b941378,
    buffer0: (GLSLEnv#451d5252, Vec2#43802a16, sampler2D#builtin) ={}> Vec4#3b941378,
}
```
*/
type t_4dccf345 = {
  type: "GLSLBuffer1";
  fragment: (arg_0: t_451d5252, arg_1: t_43802a16, arg_2: sampler2D) => t_3b941378;
  buffer0: (arg_0: t_451d5252, arg_1: t_43802a16, arg_2: sampler2D) => t_3b941378;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#451d5252 = {
    time: float#builtin,
    resolution: Vec2#43802a16,
    camera: Vec3#9f1c0644,
    mouse: Vec2#43802a16,
}
```
*/
type t_451d5252 = {
  type: "GLSLEnv";
  time: number;
  resolution: t_43802a16;
  camera: t_9f1c0644;
  mouse: t_43802a16;
};

/**
```
type Ord#2d895d64<T#:0, T#:1> = {
    "<": (A#:0, B#:1) ={}> bool#builtin,
    ">": (A#:0, B#:1) ={}> bool#builtin,
    "<=": (A#:0, B#:1) ={}> bool#builtin,
    ">=": (A#:0, B#:1) ={}> bool#builtin,
}
```
*/
type t_2d895d64<T_0, T_1> = {
  type: "2d895d64";
  h2d895d64_0: (arg_0: T_0, arg_1: T_1) => boolean;
  h2d895d64_1: (arg_0: T_0, arg_1: T_1) => boolean;
  h2d895d64_2: (arg_0: T_0, arg_1: T_1) => boolean;
  h2d895d64_3: (arg_0: T_0, arg_1: T_1) => boolean;
};

/**
```
type Neg#3c2a4898<T#:0, T#:1> = {
    "-": (A#:0) ={}> B#:1,
}
```
*/
type t_3c2a4898<T_0, T_1> = {
  type: "3c2a4898";
  h3c2a4898_0: (arg_0: T_0) => T_1;
};

/**
```
type Div#5ac12902<T#:0, T#:1, T#:2> = {
    "/": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_5ac12902<T_0, T_1, T_2> = {
  type: "5ac12902";
  h5ac12902_0: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
type Mul#1de4e4c0<T#:0, T#:1, T#:2> = {
    "*": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_1de4e4c0<T_0, T_1, T_2> = {
  type: "1de4e4c0";
  h1de4e4c0_0: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
type AddSub#b99b22d8<T#:0, T#:1, T#:2> = {
    "+": (A#:0, B#:1) ={}> C#:2,
    "-": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_b99b22d8<T_0, T_1, T_2> = {
  type: "b99b22d8";
  hb99b22d8_0: (arg_0: T_0, arg_1: T_1) => T_2;
  hb99b22d8_1: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
@ffi("Mat4") type Mat4#d92781e8 = {
    r1: Vec4#3b941378,
    r2: Vec4#3b941378,
    r3: Vec4#3b941378,
    r4: Vec4#3b941378,
}
```
*/
type t_d92781e8 = {
  type: "Mat4";
  r1: t_3b941378;
  r2: t_3b941378;
  r3: t_3b941378;
  r4: t_3b941378;
};

/**
```
type Eq#553b4b8e<T#:0> = {
    "==": (T#:0, T#:0) ={}> bool#builtin,
}
```
*/
type t_553b4b8e<T_0> = {
  type: "553b4b8e";
  h553b4b8e_0: (arg_0: T_0, arg_1: T_0) => boolean;
};

/**
```
type ToInt#c5d60378<T#:0> = {
    int: (T#:0) ={}> int#builtin,
}
```
*/
type t_c5d60378<T_0> = {
  type: "c5d60378";
  hc5d60378_0: (arg_0: T_0) => number;
};

/**
```
type ToFloat#c13d2c8a<T#:0> = {
    float: (T#:0) ={}> float#builtin,
}
```
*/
type t_c13d2c8a<T_0> = {
  type: "c13d2c8a";
  hc13d2c8a_0: (arg_0: T_0) => number;
};

/**
```
type ToStr#b416ead2<T#:0> = {
    str: (T#:0) ={}> string#builtin,
}
```
*/
type t_b416ead2<T_0> = {
  type: "b416ead2";
  hb416ead2_0: (arg_0: T_0) => string;
};

/**
```
type Some#Some<T#:10000> = {
    contents: T#:10000,
}
```
*/
type t_Some<T_10000> = {
  type: "Some";
  hSome_0: T_10000;
};

/**
```
type None#None = {}
```
*/
type t_None = {
  type: "None";
};

/**
```
type As#As<T#:10000, T#:10001> = {
    as: (T#:10000) ={}> Y#:10001,
}
```
*/
type t_As<T_10000, T_10001> = {
  type: "As";
  hAs_0: (arg_0: T_10000) => T_10001;
};
export type As<T0, T1> = t_As<T0, T1>;
export type Some<T0> = t_Some<T0>;
export type None = t_None;
export type ToStr<T0> = t_b416ead2<T0>;
export type ToFloat<T0> = t_c13d2c8a<T0>;
export type ToInt<T0> = t_c5d60378<T0>;
export type Eq<T0> = t_553b4b8e<T0>;
export type Vec2 = t_43802a16;
export type Vec3 = t_9f1c0644;
export type Vec4 = t_3b941378;
export type Mat4 = t_d92781e8;
export type AddSub<T0, T1, T2> = t_b99b22d8<T0, T1, T2>;
export type Mul<T0, T1, T2> = t_1de4e4c0<T0, T1, T2>;
export type Div<T0, T1, T2> = t_5ac12902<T0, T1, T2>;
export type Neg<T0, T1> = t_3c2a4898<T0, T1>;
export type Ord<T0, T1> = t_2d895d64<T0, T1>;
export type GLSLEnv<T0> = t_d2ea39a0<T0>;
export type GLSLEnv$1 = t_451d5252;
export type GLSLBuffer1 = t_4dccf345;
export type GLSLSceneOld<T0> = t_7eb87aa6<T0>;
export type KeyEvent = t_3648d5cc;
export type MouseButton = t_326e13e1;
export type GLSLEvent = t_4deab8f1;
export type GLSLScene<T0> = t_7769219c<T0>;