// AUTOGENERATED by 'node bootstrap.js prelude-types'
export type sampler2D = {[y: number]: {[x: number]: Vec4}};
/**
```
@ffi("Vec2") type Vec2#08f7c2ac = {
    x: float#builtin,
    y: float#builtin,
}
```
*/
type t_08f7c2ac = {
  type: "Vec2";
  x: number;
  y: number;
};

/**
```
@ffi("XY") type XY#586cd0b0<State#:0> = {
    min: Vec2#08f7c2ac,
    max: Vec2#08f7c2ac,
    update: (state: State#:0, pos: Vec2#08f7c2ac) ={}> State#:0,
}
```
*/
type t_586cd0b0<T_0> = {
  type: "XY";
  min: t_08f7c2ac;
  max: t_08f7c2ac;
  update: (arg_0: T_0, arg_1: t_08f7c2ac) => T_0;
};

/**
```
@ffi("Options") type Options#1755449c<State#:0> = {
    names: Array#builtin<string#builtin>,
    update: (state: State#:0, idx: int#builtin) ={}> State#:0,
}
```
*/
type t_1755449c<T_0> = {
  type: "Options";
  names: Array<string>;
  update: (arg_0: T_0, arg_1: number) => T_0;
};

/**
```
@ffi("Int") type Int#aa4255d4<State#:0> = {
    min: int#builtin,
    max: int#builtin,
    step: int#builtin,
    update: (state: State#:0, value: int#builtin) ={}> State#:0,
}
```
*/
type t_aa4255d4<T_0> = {
  type: "Int";
  min: number;
  max: number;
  step: number;
  update: (arg_0: T_0, arg_1: number) => T_0;
};

/**
```
@ffi("Float") type Float#4f07d626<State#:0> = {
    min: float#builtin,
    max: float#builtin,
    step: float#builtin,
    update: (state: State#:0, value: float#builtin) ={}> State#:0,
}
```
*/
type t_4f07d626<T_0> = {
  type: "Float";
  min: number;
  max: number;
  step: number;
  update: (arg_0: T_0, arg_1: number) => T_0;
};

/**
```
@ffi("Angle") type Angle#c81142a0<State#:0> = {
    step: float#builtin,
    update: (state: State#:0, angle: float#builtin) ={}> State#:0,
}
```
*/
type t_c81142a0<T_0> = {
  type: "Angle";
  step: number;
  update: (arg_0: T_0, arg_1: number) => T_0;
};

/**
```
@ffi("Vec3") type Vec3#b79db448 = {
    ...Vec2#08f7c2ac,
    z: float#builtin,
}
```
*/
type t_b79db448 = {
  type: "Vec3";
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("MouseButton") type MouseButton#5bec04f0 = {
    button: int#builtin,
    down: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_5bec04f0 = {
  type: "MouseButton";
  button: number;
  down: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/**
```
@ffi("KeyEvent") type KeyEvent#594e03e4 = {
    key: string#builtin,
    press: bool#builtin,
    ctrlKey: bool#builtin,
    shiftKey: bool#builtin,
    metaKey: bool#builtin,
}
```
*/
type t_594e03e4 = {
  type: "KeyEvent";
  key: string;
  press: boolean;
  ctrlKey: boolean;
  shiftKey: boolean;
  metaKey: boolean;
};

/*enum WidgetConfig#6699da44<State#:0> {
    Angle#c81142a0<State#:0>,
    Float#4f07d626<State#:0>,
    Int#aa4255d4<State#:0>,
    Options#1755449c<State#:0>,
    XY#586cd0b0<State#:0>,
}*/
type t_6699da44<T_0> = t_c81142a0<T_0> | t_4f07d626<T_0> | t_aa4255d4<T_0> | t_1755449c<T_0> | t_586cd0b0<T_0>;

/**
```
@ffi("Vec4") type Vec4#b1f05ae8 = {
    ...Vec3#b79db448,
    w: float#builtin,
}
```
*/
type t_b1f05ae8 = {
  type: "Vec4";
  w: number;
  z: number;
  x: number;
  y: number;
};

/**
```
@ffi("GLSLScene") type GLSLScene#6ba468c8<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#723f719e<T#:0>, GLSLEnv#723f719e<T#:0>, Array#builtin<GLSLEvent#341b62ae>) ={}> T#:0,
    render: (GLSLEnv#723f719e<T#:0>, Vec2#08f7c2ac) ={}> Vec4#b1f05ae8,
}
```
*/
type t_6ba468c8<T_0> = {
  type: "GLSLScene";
  initial: T_0;
  step: (arg_0: t_723f719e<T_0>, arg_1: t_723f719e<T_0>, arg_2: Array<t_341b62ae>) => T_0;
  render: (arg_0: t_723f719e<T_0>, arg_1: t_08f7c2ac) => t_b1f05ae8;
};

/*enum GLSLEvent#341b62ae {
    KeyEvent#594e03e4,
    MouseButton#5bec04f0,
}*/
type t_341b62ae = t_594e03e4 | t_5bec04f0;

/**
```
@ffi("GLSLScene") type GLSLSceneOld#7904844f<T#:0> = {
    initial: T#:0,
    step: (GLSLEnv#723f719e<T#:0>, GLSLEnv#723f719e<T#:0>) ={}> T#:0,
    render: (GLSLEnv#723f719e<T#:0>, Vec2#08f7c2ac) ={}> Vec4#b1f05ae8,
}
```
*/
type t_7904844f<T_0> = {
  type: "GLSLScene";
  initial: T_0;
  step: (arg_0: t_723f719e<T_0>, arg_1: t_723f719e<T_0>) => T_0;
  render: (arg_0: t_723f719e<T_0>, arg_1: t_08f7c2ac) => t_b1f05ae8;
};

/**
```
@ffi("Widget") type Widget#41fb7941<State#:0> = {
    name: string#builtin,
    config: WidgetConfig#6699da44<State#:0>,
}
```
*/
type t_41fb7941<T_0> = {
  type: "Widget";
  name: string;
  config: t_6699da44<T_0>;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#723f719e<T#:0> = {
    state: T#:0,
    time: float#builtin,
    resolution: Vec2#08f7c2ac,
    camera: Vec3#b79db448,
    mouse: Vec2#08f7c2ac,
    mouseButton: int#builtin,
}
```
*/
type t_723f719e<T_0> = {
  type: "GLSLEnv";
  state: T_0;
  time: number;
  resolution: t_08f7c2ac;
  camera: t_b79db448;
  mouse: t_08f7c2ac;
  mouseButton: number;
};

/**
```
@ffi("GLSLBuffer1") type GLSLBuffer1#1babb8a6 = {
    fragment: (GLSLEnv#a25a17de, Vec2#08f7c2ac, sampler2D#builtin) ={}> Vec4#b1f05ae8,
    buffer0: (GLSLEnv#a25a17de, Vec2#08f7c2ac, sampler2D#builtin) ={}> Vec4#b1f05ae8,
}
```
*/
type t_1babb8a6 = {
  type: "GLSLBuffer1";
  fragment: (arg_0: t_a25a17de, arg_1: t_08f7c2ac, arg_2: sampler2D) => t_b1f05ae8;
  buffer0: (arg_0: t_a25a17de, arg_1: t_08f7c2ac, arg_2: sampler2D) => t_b1f05ae8;
};

/**
```
@ffi("GLSLEnv") type GLSLEnv#a25a17de = {
    time: float#builtin,
    resolution: Vec2#08f7c2ac,
    camera: Vec3#b79db448,
    mouse: Vec2#08f7c2ac,
}
```
*/
type t_a25a17de = {
  type: "GLSLEnv";
  time: number;
  resolution: t_08f7c2ac;
  camera: t_b79db448;
  mouse: t_08f7c2ac;
};

/**
```
@unique(3) type Ord#74b229e4<A#:0, B#:1> = {
    "<": (A#:0, B#:1) ={}> bool#builtin,
    ">": (A#:0, B#:1) ={}> bool#builtin,
    "<=": (A#:0, B#:1) ={}> bool#builtin,
    ">=": (A#:0, B#:1) ={}> bool#builtin,
}
```
*/
type t_74b229e4<T_0, T_1> = {
  type: "74b229e4";
  h74b229e4_0: (arg_0: T_0, arg_1: T_1) => boolean;
  h74b229e4_1: (arg_0: T_0, arg_1: T_1) => boolean;
  h74b229e4_2: (arg_0: T_0, arg_1: T_1) => boolean;
  h74b229e4_3: (arg_0: T_0, arg_1: T_1) => boolean;
};

/**
```
@unique(3) type Neg#616f559e<A#:0, B#:1> = {
    "-": (A#:0) ={}> B#:1,
}
```
*/
type t_616f559e<T_0, T_1> = {
  type: "616f559e";
  h616f559e_0: (arg_0: T_0) => T_1;
};

/**
```
@unique(2) type Div#3b763160<A#:0, B#:1, C#:2> = {
    "/": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_3b763160<T_0, T_1, T_2> = {
  type: "3b763160";
  h3b763160_0: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
@unique(1) type Mul#02cc25c4<A#:0, B#:1, C#:2> = {
    "*": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_02cc25c4<T_0, T_1, T_2> = {
  type: "02cc25c4";
  h02cc25c4_0: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
@unique(0) type AddSub#3d436b7e<A#:0, B#:1, C#:2> = {
    "+": (A#:0, B#:1) ={}> C#:2,
    "-": (A#:0, B#:1) ={}> C#:2,
}
```
*/
type t_3d436b7e<T_0, T_1, T_2> = {
  type: "3d436b7e";
  h3d436b7e_0: (arg_0: T_0, arg_1: T_1) => T_2;
  h3d436b7e_1: (arg_0: T_0, arg_1: T_1) => T_2;
};

/**
```
@ffi("Mat4") type Mat4#0d95d60e = {
    r1: Vec4#b1f05ae8,
    r2: Vec4#b1f05ae8,
    r3: Vec4#b1f05ae8,
    r4: Vec4#b1f05ae8,
}
```
*/
type t_0d95d60e = {
  type: "Mat4";
  r1: t_b1f05ae8;
  r2: t_b1f05ae8;
  r3: t_b1f05ae8;
  r4: t_b1f05ae8;
};

/**
```
@unique(0.5383562320075749) type Eq#51ea2a36<T#:0> = {
    "==": (T#:0, T#:0) ={}> bool#builtin,
}
```
*/
type t_51ea2a36<T_0> = {
  type: "51ea2a36";
  h51ea2a36_0: (arg_0: T_0, arg_1: T_0) => boolean;
};

/**
```
@unique(0.14972816008023876) type ToInt#4caf4b64<T#:0> = {
    int: (T#:0) ={}> int#builtin,
}
```
*/
type t_4caf4b64<T_0> = {
  type: "4caf4b64";
  h4caf4b64_0: (arg_0: T_0) => number;
};

/**
```
@unique(0.8408403012585762) type ToFloat#07dae1a4<T#:0> = {
    float: (T#:0) ={}> float#builtin,
}
```
*/
type t_07dae1a4<T_0> = {
  type: "07dae1a4";
  h07dae1a4_0: (arg_0: T_0) => number;
};

/**
```
@unique(0.5661807692527293) type ToStr#64aac473<T#:0> = {
    str: (T#:0) ={}> string#builtin,
}
```
*/
type t_64aac473<T_0> = {
  type: "64aac473";
  h64aac473_0: (arg_0: T_0) => string;
};

/**
```
@unique(0) type Some#Some<T#:10000> = {
    contents: T#:10000,
}
```
*/
type t_Some<T_10000> = {
  type: "Some";
  hSome_0: T_10000;
};

/**
```
@unique(1) type None#None = {}
```
*/
type t_None = {
  type: "None";
};

/**
```
@unique(2) type As#As<T#:10000, Y#:10001> = {
    as: (T#:10000) ={}> Y#:10001,
}
```
*/
type t_As<T_10000, T_10001> = {
  type: "As";
  hAs_0: (arg_0: T_10000) => T_10001;
};
export const As_id = "As";
export type As<T0, T1> = t_As<T0, T1>;
export const Some_id = "Some";
export type Some<T0> = t_Some<T0>;
export const None_id = "None";
export type None = t_None;
export const ToStr_id = "64aac473";
export type ToStr<T0> = t_64aac473<T0>;
export const ToFloat_id = "07dae1a4";
export type ToFloat<T0> = t_07dae1a4<T0>;
export const ToInt_id = "4caf4b64";
export type ToInt<T0> = t_4caf4b64<T0>;
export const Eq_id = "51ea2a36";
export type Eq<T0> = t_51ea2a36<T0>;
export const Vec2_id = "08f7c2ac";
export type Vec2 = t_08f7c2ac;
export const Vec3_id = "b79db448";
export type Vec3 = t_b79db448;
export const Vec4_id = "b1f05ae8";
export type Vec4 = t_b1f05ae8;
export const Mat4_id = "0d95d60e";
export type Mat4 = t_0d95d60e;
export const AddSub_id = "3d436b7e";
export type AddSub<T0, T1, T2> = t_3d436b7e<T0, T1, T2>;
export const Mul_id = "02cc25c4";
export type Mul<T0, T1, T2> = t_02cc25c4<T0, T1, T2>;
export const Div_id = "3b763160";
export type Div<T0, T1, T2> = t_3b763160<T0, T1, T2>;
export const Neg_id = "616f559e";
export type Neg<T0, T1> = t_616f559e<T0, T1>;
export const Ord_id = "74b229e4";
export type Ord<T0, T1> = t_74b229e4<T0, T1>;
export const GLSLEnv_id = "723f719e";
export type GLSLEnv<T0> = t_723f719e<T0>;
export const GLSLEnv$1_id = "a25a17de";
export type GLSLEnv$1 = t_a25a17de;
export const GLSLBuffer1_id = "1babb8a6";
export type GLSLBuffer1 = t_1babb8a6;
export const Angle_id = "c81142a0";
export type Angle<T0> = t_c81142a0<T0>;
export const Int_id = "aa4255d4";
export type Int<T0> = t_aa4255d4<T0>;
export const Float_id = "4f07d626";
export type Float<T0> = t_4f07d626<T0>;
export const Options_id = "1755449c";
export type Options<T0> = t_1755449c<T0>;
export const XY_id = "586cd0b0";
export type XY<T0> = t_586cd0b0<T0>;
export const WidgetConfig_id = "6699da44";
export type WidgetConfig<T0> = t_6699da44<T0>;
export const Widget_id = "41fb7941";
export type Widget<T0> = t_41fb7941<T0>;
export const GLSLSceneOld_id = "7904844f";
export type GLSLSceneOld<T0> = t_7904844f<T0>;
export const KeyEvent_id = "594e03e4";
export type KeyEvent = t_594e03e4;
export const MouseButton_id = "5bec04f0";
export type MouseButton = t_5bec04f0;
export const GLSLEvent_id = "341b62ae";
export type GLSLEvent = t_341b62ae;
export const GLSLScene_id = "6ba468c8";
export type GLSLScene<T0> = t_6ba468c8<T0>;
export const alternates_id = "60eabfb0";
export const slider_id = "72521b0a";
export const slider$1_id = "b981a438";
export const slider$2_id = "4e421b50";
export const rgb_id = "ef68dc94";
export const rgba_id = "532a336a";
export const hsl_id = "74f2f8d1";
export const hsla_id = "2830b0d0";
export const title_id = "1b6d573e";
export const display_id = "62c51cb0";