// AUTOGENERATED by 'node bootstrap.js prelude-types'
/**
```
@ffi("AudioGen") type AudioGen#4ad6c216<State#:0> = {
    initial: State#:0,
    generate: (state: State#:0) ={}> AudioGenResponse#72421ee0<State#:0>,
}
```
*/
type t_4ad6c216<T_0> = {
  type: "AudioGen";
  initial: T_0;
  generate: (arg_0: T_0) => t_72421ee0<T_0>;
};

/**
```
@ffi("AudioGenResponse") type AudioGenResponse#72421ee0<State#:0> = {
    notes: Array#builtin<Note#17201bf2>,
    next: State#:0,
    wait: float#builtin,
}
```
*/
type t_72421ee0<T_0> = {
  type: "AudioGenResponse";
  notes: Array<t_17201bf2>;
  next: T_0;
  wait: number;
};

/**
```
@ffi("Note") type Note#17201bf2 = {
    pitch: string#builtin,
    start: float#builtin,
    duration: float#builtin,
    text: string#builtin,
}
```
*/
type t_17201bf2 = {
  type: "Note";
  pitch: string;
  start: number;
  duration: number;
  text: string;
};

/**
```
@ffi("AudioGen") type AudioGen#93153ca8<State#:0> = {
    initial: State#:0,
    generate: (state: State#:0) ={}> AudioGenResponse#03dcf15e<State#:0>,
}
```
*/
type t_93153ca8<T_0> = {
  type: "AudioGen";
  initial: T_0;
  generate: (arg_0: T_0) => t_03dcf15e<T_0>;
};

/**
```
@ffi("AudioGenResponse") type AudioGenResponse#03dcf15e<State#:0> = {
    notes: Array#builtin<Note#7ee38c94>,
    next: State#:0,
    wait: float#builtin,
}
```
*/
type t_03dcf15e<T_0> = {
  type: "AudioGenResponse";
  notes: Array<t_7ee38c94>;
  next: T_0;
  wait: number;
};

/**
```
@ffi("Note") type Note#7ee38c94 = {
    pitch: string#builtin,
    start: float#builtin,
    duration: float#builtin,
}
```
*/
type t_7ee38c94 = {
  type: "Note";
  pitch: string;
  start: number;
  duration: number;
};

/**
```
type Some#Some<T#:10000> = {
    contents: T#:10000,
}
```
*/
type t_Some<T_10000> = {
  type: "Some";
  hSome_0: T_10000;
};

/**
```
type None#None = {}
```
*/
type t_None = {
  type: "None";
};

/**
```
type As#As<T#:10000, Y#:10001> = {
    as: (T#:10000) ={}> Y#:10001,
}
```
*/
type t_As<T_10000, T_10001> = {
  type: "As";
  hAs_0: (arg_0: T_10000) => T_10001;
};
export const As_id = "As";
export type As<T0, T1> = t_As<T0, T1>;
export const Some_id = "Some";
export type Some<T0> = t_Some<T0>;
export const None_id = "None";
export type None = t_None;
export const Note_id = "17201bf2";
export type Note = t_17201bf2;
export const Note$1_id = "7ee38c94";
export type Note$1 = t_7ee38c94;
export const AudioGenResponse_id = "72421ee0";
export type AudioGenResponse<T0> = t_72421ee0<T0>;
export const AudioGenResponse$1_id = "03dcf15e";
export type AudioGenResponse$1<T0> = t_03dcf15e<T0>;
export const AudioGen_id = "4ad6c216";
export type AudioGen<T0> = t_4ad6c216<T0>;
export const AudioGen$1_id = "93153ca8";
export type AudioGen$1<T0> = t_93153ca8<T0>;