name: web

on:
    push:
        branches:
            - main
        paths:
            - 'web/**'
            - '.github/workflows/web.yml'
jobs:
    deploy:
        name: Deploy site
        runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2.3.1

        - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
          run: |
              yarn install
              yarn --cwd web build

        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@4.1.0
          with:
              branch: gh-pages
              folder: web
